export const NAV_ITEMS = [
  { id: 'workspace',  label: 'Workspace',             icon: 'workspace'  },
  { id: 'gallery',    label: 'Operations Gallery',    icon: 'gallery'    },
  { id: 'studio',     label: 'Operations Studio',     icon: 'studio'     },
  { id: 'governance', label: 'Operations Governance', icon: 'governance' },
  { id: 'command',    label: 'Operations Command',    icon: 'command'    },
];

export const SYSTEM_FLOWS = [
  {
    id: 'report_builder',
    name: 'Report Builder',
    desc: 'Build a custom report from any ServiceNow table.',
    icon: 'document',
    color: '#00BF6F',
    steps: [
      { key: 'name',        label: 'Report Name',  question: 'What would you like to name this report?',      type: 'text',   placeholder: 'e.g. Monthly Incident Summary' },
      { key: 'table',       label: 'Source Table', question: 'Which table should the report be built from?',  type: 'choice', choices: [
        { value: 'incident',        label: 'Incidents' },
        { value: 'change_request',  label: 'Change Requests' },
        { value: 'problem',         label: 'Problems' },
        { value: 'task',            label: 'Tasks' },
        { value: 'sc_request',      label: 'Service Requests' },
      ]},
      { key: 'report_type', label: 'Report Type',  question: 'What type of report would you like?',           type: 'choice', choices: [
        { value: 'list',    label: 'List Report' },
        { value: 'pie',     label: 'Pie Chart' },
        { value: 'bar',     label: 'Bar Chart' },
        { value: 'trend',   label: 'Trend Chart' },
        { value: 'pivot',   label: 'Pivot Table' },
      ]},
      { key: 'group_by',    label: 'Group By',     question: 'How should the data be grouped?',               type: 'choice', choices: [
        { value: 'assignment_group', label: 'Assignment Group' },
        { value: 'state',            label: 'State' },
        { value: 'priority',         label: 'Priority' },
        { value: 'category',         label: 'Category' },
        { value: 'assigned_to',      label: 'Assigned To' },
      ]},
      { key: 'conditions',  label: 'Conditions',   question: 'Any specific conditions to filter the data? Type "none" to skip.', type: 'text', placeholder: 'e.g. Priority is 1-Critical, or type "none"' },
    ],
  },
  {
    id: 'dashboard_builder',
    name: 'Dashboard Builder',
    desc: 'Create a performance dashboard for any focus area.',
    icon: 'workspace',
    color: '#293E40',
    steps: [
      { key: 'name',       label: 'Dashboard Name', question: 'What would you like to call this dashboard?', type: 'text', placeholder: 'e.g. IT Operations Overview' },
      { key: 'focus_area', label: 'Focus Area',     question: 'What is the primary focus area?',            type: 'choice', choices: [
        { value: 'incidents',        label: 'Incident Management' },
        { value: 'changes',          label: 'Change Management' },
        { value: 'service_requests', label: 'Service Requests' },
        { value: 'problems',         label: 'Problem Management' },
        { value: 'general',          label: 'General Operations' },
      ]},
      { key: 'timeframe',  label: 'Timeframe',      question: 'What time period should the dashboard cover?', type: 'choice', choices: [
        { value: 'last_7_days',    label: 'Last 7 Days' },
        { value: 'last_30_days',   label: 'Last 30 Days' },
        { value: 'last_90_days',   label: 'Last 90 Days' },
        { value: 'current_month',  label: 'Current Month' },
        { value: 'current_year',   label: 'Current Year' },
      ]},
      { key: 'visibility', label: 'Visibility',     question: 'Who should be able to see this dashboard?', type: 'choice', choices: [
        { value: 'private',      label: 'Private — Only Me' },
        { value: 'team',         label: 'My Groups' },
        { value: 'organization', label: 'All Operations Intelligence Users' },
      ]},
    ],
  },
  {
    id: 'data_alert',
    name: 'Data Alert',
    desc: 'Monitor a table and receive email alerts when conditions match.',
    icon: 'warning_icon',
    color: '#E57323',
    steps: [
      { key: 'name',       label: 'Alert Name',       question: 'What would you like to call this alert?',       type: 'text',   placeholder: 'e.g. Critical Incidents Alert' },
      { key: 'table',      label: 'Source Table',     question: 'Which table should be monitored?',              type: 'choice', choices: [
        { value: 'incident',       label: 'Incidents' },
        { value: 'change_request', label: 'Change Requests' },
        { value: 'problem',        label: 'Problems' },
        { value: 'task',           label: 'Tasks' },
        { value: 'sc_request',     label: 'Service Requests' },
      ]},
      { key: 'conditions', label: 'Alert Conditions', question: 'Describe the conditions that should trigger this alert:', type: 'text', placeholder: 'e.g. Priority is 1-Critical and State is New' },
      { key: 'frequency',  label: 'Check Frequency',  question: 'How often should this alert check for matching records?', type: 'choice', choices: [
        { value: 'hourly',      label: 'Every Hour' },
        { value: 'twice_daily', label: 'Twice Daily' },
        { value: 'daily',       label: 'Once Daily' },
        { value: 'weekly',      label: 'Weekly' },
      ]},
      { key: 'recipients', label: 'Recipients',       question: 'Who should receive this alert? Enter email addresses separated by commas:', type: 'text', placeholder: 'e.g. admin@company.com, team@company.com' },
    ],
  },
  {
    id: 'notification_rule',
    name: 'Notification Rule',
    desc: 'Send automatic notifications when specific events occur.',
    icon: 'send',
    color: '#00BF6F',
    steps: [
      { key: 'name',          label: 'Rule Name',       question: 'What would you like to call this notification rule?', type: 'text', placeholder: 'e.g. New Priority 1 Incident Alert' },
      { key: 'table',         label: 'Source Table',    question: 'Which table should trigger notifications?',           type: 'choice', choices: [
        { value: 'incident',       label: 'Incidents' },
        { value: 'change_request', label: 'Change Requests' },
        { value: 'problem',        label: 'Problems' },
        { value: 'task',           label: 'Tasks' },
      ]},
      { key: 'trigger_event', label: 'Trigger Event',   question: 'When should the notification be sent?', type: 'choice', choices: [
        { value: 'insert',          label: 'When a new record is created' },
        { value: 'update',          label: 'When a record is updated' },
        { value: 'state_change',    label: 'When the state changes' },
        { value: 'priority_change', label: 'When priority changes' },
      ]},
      { key: 'recipients',    label: 'Recipients',      question: 'Who should receive these notifications?', type: 'choice', choices: [
        { value: 'assigned_to', label: 'Assigned Person' },
        { value: 'watch_list',  label: 'Watch List' },
        { value: 'group',       label: 'Assignment Group' },
        { value: 'custom',      label: 'Custom Email List' },
      ]},
      { key: 'message',       label: 'Message Template', question: 'What should the notification message say?', type: 'text', placeholder: 'e.g. New Priority 1 incident: ${short_description}' },
    ],
  },
];
