// Enterprise Intelligence — hardened house style.
// Visual reference: the operations-intelligence Service Portal (dark slate sidebar,
// brand green, white topbar, soft grey canvas). Reimplemented here as a strict,
// self-contained stylesheet: every UA default is zeroed, every dimension is vh/vw,
// nothing renders from browser defaults, and no page or horizontal scroll ever exists.
// This string is injected into <head> once, at mount, by the bootstrap.
export var CSS = [
  // ---------------------------------------------------------------- reset
  // Zero every user agent default. No margins, paddings, borders, outlines,
  // list markers, native form styling, or tap highlight are inherited from the browser.
  '*,*::before,*::after{margin:0;padding:0;box-sizing:border-box;outline:0;border:0 solid transparent;',
  'background:transparent;font:inherit;color:inherit;vertical-align:baseline;',
  'list-style:none;text-decoration:none;-webkit-tap-highlight-color:transparent;',
  '-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility;',
  '-webkit-user-select:none;-moz-user-select:none;user-select:none;-webkit-touch-callout:none}',
  // the document and body are a fixed 100vh x 100vw stage: no page scroll, no horizontal scroll.
  'html,body{height:100vh;width:100vw;max-width:100vw;overflow:hidden;position:fixed;top:0;left:0}',
  'body{font-family:"Source Sans Pro","Segoe UI",Roboto,sans-serif;color:#121212;background:#F0F2F5;',
  'font-size:1.7vh;line-height:1.5}',
  'img,svg{display:block;max-width:100%}',
  'input,textarea{font-family:inherit;-webkit-user-select:text;user-select:text}',
  // hide every native scrollbar globally; scrolling is only ever inside our own styled containers.
  '::-webkit-scrollbar{width:0;height:0;background:transparent}',
  '*{scrollbar-width:none;-ms-overflow-style:none}',
  // ---------------------------------------------------------------- viewport root
  // Our root is promoted out of the platform layout to own the whole viewport.
  '#ei-root{position:fixed;top:0;left:0;right:0;bottom:0;width:100vw;height:100vh;',
  'z-index:2147483000;overflow:hidden;background:#F0F2F5;isolation:isolate}',
  // ---------------------------------------------------------------- shell
  '.ei-shell{display:grid;grid-template-columns:17vw 1fr;height:100vh;width:100vw;overflow:hidden}',
  // ---- sidebar (dark slate, exact operations-intelligence tone) ----
  '.ei-side{background:#293E40;display:flex;flex-direction:column;height:100vh;overflow:hidden}',
  '.ei-brand{display:flex;align-items:center;gap:0.9vw;height:8vh;flex:0 0 auto;padding:0 1.3vw;',
  'border-bottom:0.1vh solid rgba(255,255,255,0.08)}',
  '.ei-brand-mark{width:2.6vh;height:2.6vh;flex:0 0 auto;border-radius:0.55vh;background:#00BF6F;',
  'display:flex;align-items:center;justify-content:center;color:#fff;font-weight:800;font-size:1.6vh}',
  '.ei-brand-txt{color:#fff;font-weight:700;font-size:1.85vh;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.ei-nav{display:flex;flex-direction:column;padding:1.4vh 0;flex:1 1 auto;min-height:0;overflow-y:auto}',
  '.ei-nav-item{display:flex;align-items:center;gap:0.9vw;padding:1.5vh 1.3vw;cursor:pointer;',
  'color:#B9C6C6;font-size:1.75vh;font-weight:600;border-left:0.28vw solid transparent;',
  'transition:background .15s,color .15s}',
  '.ei-nav-item:hover{background:rgba(255,255,255,0.07);color:#fff}',
  '.ei-nav-item.on{background:rgba(0,191,111,0.20);color:#fff;border-left-color:#00BF6F}',
  '.ei-nav-ico{width:1.75vh;height:1.75vh;flex:0 0 auto;display:flex;align-items:center;justify-content:center}',
  '.ei-nav-ico svg{width:100%;height:100%}',
  '.ei-side-foot{flex:0 0 auto;padding:1.2vh 1.3vw;border-top:0.1vh solid rgba(255,255,255,0.08);',
  'display:flex;flex-direction:column;gap:1vh}',
  '.ei-portal-btn{display:flex;align-items:center;justify-content:center;gap:0.7vw;width:100%;',
  'padding:1.2vh 0;border-radius:0.6vh;background:rgba(255,255,255,0.06);color:#DFF5EC;',
  'font-size:1.55vh;font-weight:600;cursor:pointer;transition:background .15s}',
  '.ei-portal-btn:hover{background:rgba(0,191,111,0.22);color:#fff}',
  '.ei-portal-btn .ei-nav-ico{width:1.55vh;height:1.55vh}',
  '.ei-user{display:flex;align-items:center;gap:0.8vw}',
  '.ei-avatar{width:3.1vh;height:3.1vh;flex:0 0 auto;border-radius:50%;background:#00BF6F;color:#fff;',
  'display:flex;align-items:center;justify-content:center;font-weight:700;font-size:1.4vh}',
  '.ei-user-meta{display:flex;flex-direction:column;min-width:0}',
  '.ei-user-name{color:#fff;font-size:1.55vh;font-weight:600;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.ei-user-role{color:#8AA0A0;font-size:1.3vh;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  // ---- main column ----
  '.ei-main{display:flex;flex-direction:column;height:100vh;min-width:0;overflow:hidden}',
  '.ei-head{height:8vh;flex:0 0 auto;background:#fff;border-bottom:0.1vh solid #DCDCDC;',
  'display:flex;align-items:center;justify-content:space-between;padding:0 1.8vw}',
  '.ei-crumb{display:flex;flex-direction:column;gap:0.2vh;min-width:0}',
  '.ei-crumb-t{font-size:2vh;font-weight:700;color:#121212;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.ei-crumb-s{font-size:1.4vh;color:#6E6E6E;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}',
  '.ei-head-r{display:flex;align-items:center;gap:1.2vw;flex:0 0 auto}',
  '.ei-icon-btn{width:3.4vh;height:3.4vh;border-radius:0.6vh;display:flex;align-items:center;justify-content:center;',
  'color:#6E6E6E;cursor:pointer;transition:background .15s,color .15s}',
  '.ei-icon-btn:hover{background:#F0F2F5;color:#121212}',
  '.ei-icon-btn .ei-nav-ico{width:2vh;height:2vh}',
  // ---- content canvas ----
  '.ei-body{flex:1 1 auto;min-height:0;background:#F0F2F5;overflow:hidden;display:flex}',
  // Assistant section: catalog (left) + chat (right), balanced two panels.
  '.ei-assist{display:grid;grid-template-columns:1fr 1fr;gap:1.6vw;width:100%;height:100%;padding:2.2vh 1.8vw}',
  '.ei-panel{background:#fff;border:0.1vh solid #DCDCDC;border-radius:1vh;display:flex;flex-direction:column;',
  'min-height:0;overflow:hidden}',
  '.ei-panel-h{flex:0 0 auto;padding:1.9vh 1.4vw;border-bottom:0.1vh solid #DCDCDC;display:flex;',
  'flex-direction:column;gap:0.3vh}',
  '.ei-panel-t{font-size:1.95vh;font-weight:700;color:#121212;display:flex;align-items:center;gap:0.6vw}',
  '.ei-panel-t .ei-nav-ico{width:1.95vh;height:1.95vh;color:#00895E}',
  '.ei-panel-s{font-size:1.45vh;color:#6E6E6E}',
  // ---- catalog ----
  '.ei-cat{flex:1 1 auto;min-height:0;overflow-y:auto;padding:1.8vh 1.4vw;display:flex;flex-direction:column;gap:1.4vh}',
  '.ei-cat-grp{font-size:1.35vh;font-weight:700;color:#6E6E6E;letter-spacing:0.08vw;text-transform:uppercase}',
  '.ei-card{border:0.1vh solid #DCDCDC;border-radius:0.9vh;padding:1.7vh 1.3vw;cursor:pointer;display:flex;',
  'gap:1.1vw;align-items:flex-start;transition:border-color .15s,box-shadow .15s,transform .15s}',
  '.ei-card:hover{border-color:#00BF6F;box-shadow:0 0.5vh 1.8vh rgba(0,137,94,0.12);transform:translateY(-0.2vh)}',
  '.ei-card-ico{width:4.2vh;height:4.2vh;flex:0 0 auto;border-radius:0.8vh;background:#EAF7F1;color:#00895E;',
  'display:flex;align-items:center;justify-content:center}',
  '.ei-card-ico .ei-nav-ico{width:2.2vh;height:2.2vh}',
  '.ei-card-b{display:flex;flex-direction:column;gap:0.5vh;min-width:0}',
  '.ei-card-t{font-size:1.8vh;font-weight:700;color:#121212}',
  '.ei-card-d{font-size:1.45vh;color:#6E6E6E;line-height:1.5}',
  // ---- chat ----
  '.ei-chat{flex:1 1 auto;min-height:0;display:flex;flex-direction:column}',
  '.ei-chat-scroll{flex:1 1 auto;min-height:0;overflow-y:auto;padding:2vh 1.4vw;display:flex;',
  'flex-direction:column;gap:1.3vh}',
  // a single custom scrollbar, only inside the two containers that genuinely overflow.
  '.ei-cat::-webkit-scrollbar,.ei-chat-scroll::-webkit-scrollbar{width:0.55vw;height:0}',
  '.ei-cat,.ei-chat-scroll{scrollbar-width:thin;-ms-overflow-style:auto}',
  '.ei-cat::-webkit-scrollbar-thumb,.ei-chat-scroll::-webkit-scrollbar-thumb{background:#CFE0DB;border-radius:1vh}',
  '.ei-cat::-webkit-scrollbar-thumb:hover,.ei-chat-scroll::-webkit-scrollbar-thumb:hover{background:#00BF6F}',
  '.ei-msg{max-width:82%;padding:1.3vh 1.2vw;border-radius:1.1vh;font-size:1.6vh;line-height:1.55;',
  'white-space:pre-wrap;word-break:break-word;-webkit-user-select:text;user-select:text}',
  '.ei-msg.user{align-self:flex-end;background:#00BF6F;color:#fff;border-bottom-right-radius:0.3vh}',
  '.ei-msg.asst{align-self:flex-start;background:#F0F2F5;color:#121212;border-bottom-left-radius:0.3vh}',
  '.ei-welcome{margin:auto;text-align:center;color:#6E6E6E;display:flex;flex-direction:column;',
  'align-items:center;gap:1.2vh;padding:2vh;max-width:80%}',
  '.ei-welcome-mark{width:6.5vh;height:6.5vh;border-radius:50%;background:#EAF7F1;color:#00895E;',
  'display:flex;align-items:center;justify-content:center}',
  '.ei-welcome-mark .ei-nav-ico{width:3.2vh;height:3.2vh}',
  '.ei-welcome-t{font-size:2.1vh;font-weight:700;color:#121212}',
  '.ei-welcome-d{font-size:1.55vh;line-height:1.6}',
  '.ei-typing{align-self:flex-start;display:flex;gap:0.45vw;padding:1.4vh 1.2vw}',
  '.ei-typing i{width:0.85vh;height:0.85vh;border-radius:50%;background:#00BF6F;opacity:.35;animation:eidot 1s infinite}',
  '.ei-typing i:nth-child(2){animation-delay:.15s}.ei-typing i:nth-child(3){animation-delay:.3s}',
  '@keyframes eidot{0%,70%,100%{opacity:.3;transform:translateY(0)}35%{opacity:1;transform:translateY(-0.4vh)}}',
  '.ei-chat-in{flex:0 0 auto;border-top:0.1vh solid #DCDCDC;padding:1.4vh 1.2vw;display:flex;gap:0.8vw;align-items:flex-end}',
  '.ei-field{flex:1 1 auto;background:#F0F2F5;border-radius:1vh;padding:1.3vh 1.1vw;font-size:1.6vh;',
  'color:#121212;resize:none;max-height:14vh;line-height:1.5;border:0.1vh solid transparent}',
  '.ei-field:focus{border-color:#00BF6F;background:#fff}',
  '.ei-field::placeholder{color:#9AA6A6}',
  '.ei-send{width:4.4vh;height:4.4vh;flex:0 0 auto;border-radius:1vh;background:#00BF6F;color:#fff;',
  'display:flex;align-items:center;justify-content:center;cursor:pointer;transition:background .15s}',
  '.ei-send:hover{background:#007A4C}',
  '.ei-send .ei-nav-ico{width:2.1vh;height:2.1vh}',
  // ---- generic section (non-Assistant tabs): content + right assistant rail ----
  '.ei-sec{display:grid;grid-template-columns:1fr 26vw;gap:1.6vw;width:100%;height:100%;padding:2.2vh 1.8vw}',
  '.ei-sec-main{background:#fff;border:0.1vh solid #DCDCDC;border-radius:1vh;padding:2.4vh 1.8vw;overflow:hidden;',
  'display:flex;flex-direction:column;gap:1.4vh}',
  '.ei-sec-t{font-size:2vh;font-weight:700;color:#121212}',
  '.ei-sec-d{font-size:1.55vh;color:#6E6E6E;line-height:1.6}',
  '.ei-stat-row{display:grid;grid-template-columns:repeat(2,1fr);gap:1.2vw}',
  '.ei-stat{border:0.1vh solid #DCDCDC;border-radius:0.9vh;padding:1.6vh 1.3vw;display:flex;flex-direction:column;gap:0.4vh}',
  '.ei-stat-v{font-size:2.6vh;font-weight:700;color:#00BF6F;line-height:1}',
  '.ei-stat-l{font-size:1.35vh;color:#6E6E6E;text-transform:uppercase;letter-spacing:0.05vw}'
].join('');
